meta:
  provider: aws
  region: us-east-1
  clusterName: useast1.dev.bflobox.com
  name: bflobox-api
  namespace: bflobox
  environment: development
containers:
  bfloBoxApi:
    name: bflobox-api
    image:
      repository: 418118555604.dkr.ecr.us-east-1.amazonaws.com/bflobox-api
      # Why is this CHANGETHIS? Mainly because the tag `latest` is an anti-pattern and I override this value at the helm upgrade step in CI
      tag: CHANGETHIS
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    port: 8080
    replicas: 1
loadBalancer:
  cert: arn:aws:acm:us-east-1:418118555604:certificate/d9b4506a-04d1-4079-8f95-53c28a9121e1