name: Lint & Test Web

on:
  pull_request:
    branches:
    - master

jobs:
  lint_and_test_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example/bflobox
    steps:
    - uses: actions/checkout@v1
    - name: Build Web
      run: make build
    - name: Lint API
      run: make lint
    - name: Test API
      run: make test

  lint_and_test_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example/api
    steps:
    - uses: actions/checkout@v1
    - name: Build API
      run: make build
    - name: Build Utils
      run: make build-utils
    - name: Lint API
      run: make lint
    - name: Test API
      run: make test
